<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>dns-Recovered.ico</ApplicationIcon>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<FileVersion>1.0.1</FileVersion>
		<AssemblyVersion>1.0.1</AssemblyVersion>
		<Version>1.0.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="dns-Recovered.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.10" />
		<PackageReference Include="System.Management" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Database\Model\" />
		<Folder Include="Database\Context\" />
	</ItemGroup>

</Project>
